name: lms
description: " A Library Management System."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  flutter_svg: ^2.0.17
  logger: ^2.5.0
  shimmer: ^3.0.0 # For shimmer effect
  supabase_flutter: ^2.9.0 # An Online Database
  image_picker: ^1.1.2
  another_flushbar: ^1.12.30 # For Snack bar
  cached_network_image: ^3.4.1

  # For local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4

  google_sign_in: ^6.3.0
  toggle_switch: ^2.3.0
  carousel_slider: ^5.0.0
  lucide_icons: ^0.257.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test:
  mocktail: ^1.0.4
  change_app_package_name: ^1.5.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/